# Generated by Django 5.0.14 on 2026-06-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('patient_absence', 'Ausencia do paciente'), ('trainee_absence', 'Ausencia do estagiario'), ('patient_request', 'Solicitacao do paciente'), ('trainee_request', 'Solicitacao do estagiario'), ('technical_issue', 'Problema tecnico'), ('rescheduled', 'Reagendada'), ('other', 'Outro')], max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
